microscope/cleaners.py
microscope/find_citations.py
microscope/reporter_tokenizer.py
microscope/utils.py
tests/test_FindTest.py
tests/test_UtilsTest.py

There's currently a few different text cleaning things happening that I know of:
* html is automatically stripped by default
* tokenizer collapses repeated spaces with `text = re.sub(" +", " ", text)`
* tokenizer removes repeated underscores with 
```
text = re.sub(r"__+", "", text)
```
This stuff seems likely to be caller-specific, e.g. CAP will want different things from CL. I'm offering this PR for discussion as one way to refactor. Here's what it includes:
* Html now defaults to False. I like the idea of including this in the library because it's finicky to get right, but I'd want to opt in if I knew I had HTML.
* Collapsing spaces is a good default, and makes sense as a separate pass before the text goes to tokenize(). Now runs as a separate function behind a flag defaulting to True. …

Factor out text cleaning

---

microscope/find_citations.py
microscope/helpers.py
microscope/models.py
microscope/reporter_tokenizer.py
microscope/utils.py
tests/test_FindTest.py
tests/test_TokenizeTest.py
tests/test_UtilsTest.py

I believe we don't need file encoding lines in python 3 since the default is utf8, and don't need shebangs for files that don't make sense to mark executable. Just a quick cleanup PR -- no big deal to close if you want to keep these around for whatever reason.

(cleanup) drop header lines

---

microscope/find_citations.py
microscope/helpers.py
microscope/reporter_tokenizer.py

This is a first quick pass at improving performance, split into three commits from most to least useful. The result is a ~90% runtime reduction (10x faster) on a large test case.
* Cache the set of valid reporter strings in `microscope.helpers.REPORTER_STRINGS`. Reduces runtime by about 2/3.
* Use a simpler regex to check for "supra" strings instead of using `strip_punct()`. Reduces remaining runtime by about 2/3. This is a functional change, as it will match some "`<non-alphanum>supra<non-alphanum>`" strings that the old code wouldn't. I think that's not a big deal in practice though.
* Also note the supra line still isn't that fast, accounting for 7% of total runtime. In a later refactor I think determining token types might want to live in `tokenize` so it can be done in one pass, both …

Initial performance improvements

---

eyecite/models.py
pyproject.toml
tests/test_ModelsTest.py

I realized that I forgot to transfer the test for citation hashing from CL to this repo. But, as I was doing so, I also realized that our implementation of `Citation.fuzzy_hash()` is confusing and liable to cause errors for those not familiar with its origin.
See the [Python docs](https://docs.python.org/3/reference/datamodel.html#object.__hash__) on this matter:
> If a class does not define an \_\_eq\_\_() method it should not define a \_\_hash\_\_() operation either; if it defines \_\_eq\_\_() but not \_\_hash\_\_(), its instances will not be usable as items in hashable collections.
Currently, we implement `__eq__()` but not `__hash__()`, meaning that `Citation` objects cannot be used in hashable collections (as the docs warn). Thus, if the user were to do something like `citation1 in …

Fix citation hashing

---

README.rst
eyecite/cleaners.py
tests/test_AnnotateTest.py
tests/test_FindTest.py
tests/test_UtilsTest.py

I believe the tokenizer should support matching citation strings that might break across lines or be internally separated by other whitespace characters.
The full and shortform tests that I added won't pass without the changes in this PR. (The supra and id ones pass fine already -- because we're just matching single tokens for them, no whitespace involved -- but I added tests for them too for good measure.)

fix(tokenizer): Matches citations across line breaks.

---

eyecite/models.py
eyecite/tokenizers.py
poetry.lock
pyproject.toml
requirements.txt
tests/test_FindTest.py
tests/test_TokenizeTest.py

This is a first pass at using the `"regexes"` field from reporters-db to extract non-standard citations. E.g. from the tests:
```
('blah blah Bankr. L. Rep. (CCH) P12,345. blah blah',
[case_citation(2, volume='', reporter='Bankr. L. Rep.',
reporter_found='Bankr. L. Rep. (CCH)', page='P12,345')]),
('blah blah, 2009 12345 (La.App. 1 Cir. 05/10/10). blah blah',
[case_citation(2, volume='2009', reporter='La.App. 1 Cir.',
reporter_found='(La.App. 1 Cir.', page='12345')]),
```
As you can see, volume can sometimes now end up as an empty string. Custom regexes can also extract extra data -- in the last test example `cite.token.extra_match_groups == {"date_filed": "05/10/10"}`.
There's a few limitations of the existing reporters-db format where I had to make arbitrary choices:
**Multiple …

Use custom regexes from reporters-db

---

eyecite/annotate.py
poetry.lock
pyproject.toml
tests/assets/opinion.txt
tests/test_AnnotateTest.py

Per #34, this PR adds support for an alternate diffing library in `annotate()`. We now have three options (though probably want to converge on one):
* By default, `annotate()` uses built in Python diffing.
* If you `pip install diff_match_patch`, then `annotate(use_dmp=True)` uses [this pure-python DMP library](https://pypi.org/project/diff-match-patch/).
* If you instead `pip install diff_match_patch_python`, then `annotate(use_dmp=True)` uses [this C++ DMP library](https://pypi.org/project/diff_match_patch_python/). (Note for testing that you must `pip uninstall` the other one first -- they don't coexist.)
The speed difference is *very* significant: in my test on the text in #34, the first option took 17,000ms to call annotate(), the second option took 700ms, and the third option took …

Support diff_match_patch_python library

---

README.rst
eyecite/test_factories.py
tests/test_FindTest.py
tests/test_ModelsTest.py

Re #32, simple change to expose the test factories in the packaged version of eyecite. Impetus is that I'm using them in CL, but I imagine others might want to use them too when writing their own tests.

Issue 32 expose test factories

---

eyecite/models.py
eyecite/tokenizers.py
tests/test_TokenizeTest.py

This fixes #46. As @mattdahl suggested, that bug is because the full regexes for "see" and "id." overlap (they both capture the space between them, but then ignore it by only grabbing what's in the match group). Unlike the regexes, the tokens generated from each regex have correct start and end offsets and don't overlap, so the core fix was just a one-liner to compare offsets on `extractor.get_token(m)` instead of the offsets of `m.span()` itself.
What made that tricky was that hyperscan works on bytes instead of strings, and dealing with the byte offsets was complicating everything. I realized that I could instead update the byte offsets right after they came out of hyperscan, and make it easier to work with everything downstream. Thus began refactoring.
So this has a bunch of changed …

Handle side-by-side tokens with overlapping regexes

---

eyecite/test_factories.py

I should have included this in my previous PR, but this is just a tweak to make the `source_text` parameter optional in the factory functions. When creating mock objects, it is not necessary that a token's data be anything other than `None` (though the user is welcome to set it to something else if they want). The `case_citation()` function already has `None` as its default; this change just brings the other functions in line.

Make source_text parameter optional in test factories

---

README.rst
eyecite/annotate.py
tests/test_AnnotateTest.py

I ran into an edge case for CAP where citations can contain page numbers:
`1 U.S. <a class="page-label" ...>123</a>1`
I have a cleaning step that removes these links and their text for cite extraction, but then annotating doesn't work -- I get `<a href="/us/1/1/">1 U.S. <a class="page-label" ...>123</a>1</a>`, which is bad HTML, and `unbalanced_tags` can't help.
This PR adds an `annotator` argument to `annotate()` so I can pass in a callable with custom handling for this case -- see the edited Readme for an example.
As usual I'd welcome naming suggestions if `annotator` is confusing.

Allow custom annotation formats

---

eyecite/find_citations.py
eyecite/helpers.py
tests/test_FindTest.py

This PR adds bounds checks and tests for a set of partial citation inputs that currently raise IndexError from `get_citations` -- 
```
'123 supra.'
', supra.'
', 1 U.S., at 1'
'1 U.S., at 1'
'v. Bar, 1 U.S. 1'
'1 U.S. 1 ('
```
The one functional change is that `get_citations('supra.')` now returns a `SupraCitation` with no antecedent, where before it would have returned nothing. I think it's less surprising to have `get_citations('supra.')` do the same thing as `get_citations('no cite supra.')` instead of being a special case.

Avoid scanning tokens past end of input

---

eyecite/annotate.py
tests/test_AnnotateTest.py

This PR is a simple fix to address the problem I identified in #54.
Before, we would always use `bisect_right()` to determine the index of the updater function to use when calculating the new offsets for an annotation. This makes sense when we are updating the _start_ offset for a string, because we want to use the updater whose position is `bisect_right() - 1` and `bisect_right()` returns the index that is one to the right of the offset index. However, this causes a kind of off-by-one error with the _end_ offset of a string, since we now want the index in the other (leftward) direction instead. Hence, I think we need to use `bisect_left()` for the end offsets, which returns the index that is one to the left of the offset index.
Apologies if this is confusing, it's difficult for me to …

fix(annotate): Toggles bisect method by start/end update; fixes #54.

---

eyecite/helpers.py
tests/test_FindTest.py

This updates year parsing to fix a ValueError CAP ran into on the input "123 U.S. 456 (196⁴)", and makes some other changes along the way.
* No longer use `isdigit`, which I just learned returns True for unicode digit characters, just attempt int() conversion and catch ValueError.
* Don't accept all strings that start with four digit characters, so we don't parse `"2000000"` as `2000`. If there are things we're trying to handle with `r"(\d{4}).*"` let's use a tighter regex.
* Bump the minimum date back to 1600, since CAP goes back to 1658.
* Add a maximum date of the current year.

Update year parsing

---

eyecite/find_citations.py
eyecite/helpers.py
eyecite/models.py
eyecite/test_factories.py
eyecite/tokenizers.py
eyecite/utils.py
poetry.lock
pyproject.toml
tests/test_AnnotateTest.py
tests/test_FindTest.py
tests/test_TokenizeTest.py
tests/test_UtilsTest.py

As usual I started pulling a string and ended up reknitting the sweater, so this is way too big to review -- apologies yet again. :)
This PR grows out of #56, regarding excess roman numeral page matches, and #52, regarding tightening full-cite matches to not match patterns like "A1 P 1A" as "1 P. 1". Along the way to getting those working I ended up building a useful helper function for running regular expressions against the extracted tokens, and using it to more precisely extract pin cites, and I threw in a bonus feature to extract citation parentheticals as well.
**TL;DR -- API changes:**
Here's what I know of that visibly changes with this PR when calling `get_citations()`:
* Attribute changes:
* All citations gain a `pin_cite` attribute, which includes the entire pin cite ("at 1, 2-3 …

Tighten page number matching; extend pin cite matching; extract parentheticals

---

pyproject.toml

I don't know if this is actually correct, but if I try to install eyecite in editable mode like "pip install -e /path/to/eyecite", I get "ModuleNotFoundError: No module named 'setuptools'" unless this is included. This way it seems to work.

Add setuptools to build-system

---

README.rst
eyecite/find_citations.py
eyecite/helpers.py
eyecite/models.py
eyecite/regexes.py
eyecite/resolve.py
eyecite/test_factories.py
eyecite/tokenizers.py
eyecite/utils.py
poetry.lock
pyproject.toml
tests/test_AnnotateTest.py
tests/test_FindTest.py
tests/test_RegexTest.py
tests/test_ResolveTest.py
tests/test_TokenizeTest.py
tests/test_UtilsTest.py

This adds extraction of laws.json and journals.json patterns from reporters_db:
```
>>> get_citations("1 U.S. 1. Mass. Gen. Laws ch. 1, § 2. 1 Minn. L. Rev. 2.")
[FullCaseCitation('1 U.S. 1', groups={'volume': '1', 'reporter': 'U.S.', 'page': '1'}),
LawCitation('Mass. Gen. Laws ch. 1, § 2', groups={'reporter': 'Mass. Gen. Laws', 'chapter': '1', 'section': '2'}),
JournalCitation('1 Minn. L. Rev. 2', groups={'volume': '1', 'reporter': 'Minn. L. Rev.', 'page': '2'})]
```
Yay! Now some questions ...
**Question: class hierarchy?**
Here's the class hierarchy I currently have for citations, with the ones we actually instantiate in bold:
* CitationBase
* ResourceCitation: stuff done by full and short cites that matched a pattern from reporters_db
* FullCitation: label for things that are full …

Add extraction of laws.json and journals.json patterns from reporters_db

---

CHANGES.md
README.rst
eyecite/__init__.py
eyecite/models.py
eyecite/utils.py
tests/test_UtilsTest.py

Not sure if this belongs in the library, but when I was adding journals and statutes I found it useful to dump the results for a bunch of CAP cases and eyeball them to see what looked wrong. That resulted in this helper function `dump_citations(cites, text, context_chars=30)`, which has highlighted output that looks like this:
This seemed useful enough that I thought I'd throw it in to see if it helps other folks as well -- mostly for us developing the library but maybe also helpful if you're using eyecite for your own purposes.

Add dump_citations helper

---

README.rst
eyecite/helpers.py
eyecite/resolve.py

This updates the readme intro/background/quickstart a little bit, including just a little bit of Caselaw Access Project horn tooting so I wouldn't feel left out. :)
This also adds a Tutorial section after Quickstart, walking through a full-featured industrial example of using the library. I thought it would be useful to see why all of the parts exist and how they're supposed to fit together in production.
Rendered rst in case that's easier to read: https://github.com/jcushman/eyecite/tree/quickstart

Readme intro & tutorial

---

eyecite/find_citations.py
eyecite/helpers.py
eyecite/regexes.py
tests/test_FindTest.py
tests/test_UtilsTest.py

Note: This description has been rewritten to reflect the new contents of this PR.
This PR improves and expands parenthetical support. It also partially fixes an issue in the test code causing tests to silently fail. Specifically, it does the following things:
- Modifies the parenthetical matching regex to allow for proper capturing of parentheticals with nested parentheticals.
- For example: a citation like 'foo v. bar, 1 U.S. 3 (2021) (quoting baz (Holmes, J., concurring) and) 
- Because we no longer cut off matching at the first closing paren found in the string, the regex could potentially capture more than one parenthetical (e.g. the parenthetical for `foo v. bar, 1 U.S. 3 (2021) (overruling baz) and something else (unrelated parenthetical).` would be captured as `overruling baz) and …

Improve parenthetical functionality and resolve silent test failures

---

eyecite/test_factories.py
tests/test_FindTest.py
tests/test_ResolveTest.py

Here's a couple of cleanup items following @ProbablyFaiz's discovery that I broke the test harness 😣:
* Update the short-citation test fixture to default court to `"scotus"` when reporter is `"U.S."`, the same way full citations already do. This removes a bunch of `'court': 'scotus'` from the individual tests.
* Go ahead and stop explicitly checking `cite.index` values -- checking those makes the test cases more annoying to write, and if `index` was wrong they would fail anyway because metadata extraction would fail. (The same is true for not checking `span()` -- if that was wrong the annotation test cases would fail.) Since we're not checking `index`, we can further streamline the test cases by defaulting `index` to `0` instead of explicitly setting it.

Test cleanup

---

eyecite/find_citations.py
eyecite/helpers.py
eyecite/models.py
eyecite/regexes.py
tests/test_FindTest.py

Following up on #62:
> One upshot of the way I implemented this functionality in extract_pin_citation is that parentheticals attached to Id and Supra citations are now also captured. They are not used, however, because the Id and Supra citation classes don't currently have a parenthetical field in their metadata. I'm a little wary of tampering with a class model I don't fully understand at the moment, so I'll leave that to you guys.
This sets `cite.metadata.parenthetical` for id. and supra cites.

Extract parentheticals for supra and id cites

---

eyecite/helpers.py
tests/test_FindTest.py

`process_parenthetical` was missing from `add_law_metadata` and `add_journal_metadata`, so `LawCitation` and `JournalCitation` were capturing text beyond the end of their actual parentheticals.
Also in this PR:
* `process_parenthetical` returns `None` for empty parentheticals to make the calling sites less verbose. 
* Update tests to ensure that law/journal/supra/id cites don't capture more of the parenthetical than they should.

Call process_parenthetical for laws and journals

---

eyecite/test_factories.py
poetry.lock
pyproject.toml
tests/test_FindTest.py

The latest reporters-db code ([PR](https://github.com/freelawproject/reporters-db/pull/59)) changed the match groups for `Bankr. L. Rep. (CCH) P12,345` so they come in as `groups={"volume": None ...}` instead of not having a volume key. This is because CCH cites sometimes have a volume and sometimes don't, so there's now an optional match group to check for it.
So, this PR just updates the eyecite tests to expect that `"volume": None` value. It will pass against the latest reporters-db but not against the one on PyPI, so I'm not sure how you want to sequence things.

Fix Bankr. L. Rep. test for new reporters-db

---

CHANGES.md
poetry.lock
pyproject.toml

@jcushman could you give this a look? I'm attempting to release version 2.2.0, with the courts-db fix you landed and with all the API reorganization that you did back in #64. 
I think I summarized well, but there was a lot in there and I think a second set of eyes might pick up one something I missed.

v2.2.0 release and bump courts-db

---

CHANGES.md
eyecite/models.py
eyecite/regexes.py
eyecite/tokenizers.py
poetry.lock
pyproject.toml
tests/test_FindTest.py

I noticed that we weren't getting short cites for the `Mich.` reporter, which turns out to be because that reporter has a non-standard volume number in its regex, and we currently only look for short cites for the standard regex.
So this PR does three related things:
* Add a `short_cite_re` function to more flexibly generate short-cite regexes from full cite regexes. Currently this is only slightly more flexible than before, but does successfully work for `Mich.`: it tries to insert an " at " between the `(?P<reporter>...)` and `(?P<page>...)` groups. This could get smarter if we figure out rules for other cite formats.
* When generating regexes for variant editions, put them in a single regex like `(?P<reporter>Mich|Mich Foo|etc.)` instead of making a separate regex for each of them. …

More flexible short cite generation

---

eyecite/regexes.py
tests/test_FindTest.py

When reindexing CAP we ran into [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html) in the pin cite regex -- metadata extraction would take forever on long pin cites like `'2277, 2278, 2279, 2280, 2281, 2282, 2283, 2284, 2286, 2287, 2288, 2289, 2290, 2291'`. Turns out the core problem is the regex is looking for an optional `, ` between every page number, which gave it a huge number of options to check in that example, when it needs to look for optional `, ` only before the first page number, and mandatory `, ` for subsequent page numbers.
Also in this PR, a tweak to `YEAR_REGEX` so `{YEAR_REGEX}?` will work as expected.

Avoid backtracking in pin cite regex

---

README.rst

This PR makes several improvements to our README.
First, re #94, it adds to the top a clear list of the four core functions of eyecite: extraction, aggregation (resolution), annotation, and cleaning.
Second, re #95, it clarifies the tutorial regarding the hypothetical "database" and other confusing items. All the code in the tutorial is now definitely run-able by the reader, except for two sections that offer psuedo-code for expanded functionality (the `resolutions2` and `annotations2` sections). I also attempted to clarify those sections themselves by providing more details about how one might integrate with an external database or API. It should hopefully be clear that eyecite works fine without doing that, but the pseudo-code should still be helpful for users trying to exploit that …

Improve tutorial and README

---

README.rst

Current examples raise: `TypeError: 'module' object is not callable`. It looks like the name of the function was changed to annotate_citations and the README was not updated.

Update README.rst to reflect name of annotate_citations function

---

eyecite/helpers.py
eyecite/models.py
tests/test_FindTest.py

I created a new full_span() function that takes into account the whole citation (including plaintiff, defendant, and post_citation).
We still have an issue when plaintiff name is made of several words, or when the extra attribute contains too much text, but this can be solved independently.
Have a good weekend !

Fixed parenthesis, added full_span function and test

---

CHANGES.md
eyecite/models.py
eyecite/test_factories.py

In #110, eighteen months ago, we renamed `NonopinionCitation` to `UnknownCitation` and implemented a deprecation warning signaling that support for the old object would end in version 2.5.0. We're now on 2.5.2, so I think it is safe to remove this old code.

Implement NonopinionCitation deprecation plan (#110)

---

eyecite/models.py
eyecite/test_factories.py
eyecite/utils.py
tests/test_ModelsTest.py

This PR does three things:
1) Citations with normalized/corrected reporters (e.g., `1 U.S. 1` versus `1 U. S. 1`) are now treated as equal (#147)
2) Citations with nominative reporters (e.g., `5 U.S. 137` versus `5 U.S. (1 Cranch) 137` are now treated as equal (#154)
3) Citation hashes are now reproducible/deterministic across runs (https://github.com/freelawproject/eyecite/issues/147#issuecomment-1488381874)
In terms of implementation, here's what's changed:
- The old `comparison_hash()` method that a few classes had has been removed entirely. This was originally intended to essentially be a private method for `Resource` objects to call, but the name was confusing and could have been misinterpreted by a causal user as a public method that should be used for general comparisons. Going …

Issue 147, 154 - Improve citation object hashing behavior

---

.github/workflows/pdoc.yml

This PR updates the pdoc.yml file to change the name of the action of the deploy step. It should be `JamesIves/github-pages-deploy-action@v4` according to the [documentation](https://github.com/JamesIves/github-pages-deploy-action?tab=readme-ov-file#getting-started-airplane), but we're using `jamesIves/github-pages-deploy-action@4.5.0 `instead.

chore(workflow): Updates the pdoc.yml to fix the deploy step

---

.github/workflows/pdoc.yml

There is a [known issue with pdoc3](https://github.com/pdoc3/pdoc/issues/392#issuecomment-1872475490) that prevents it from functioning correctly with Python 3.12. When attempting to execute the command `pdoc module`, the following error occurs: `ModuleNotFoundError: No module named 'distutils'`. 
As a workaround, temporarily downgrading the python version within the action to `3.11` should allow it to complete successfully.

chore(workflow): Downgrade the python version in the pdoc action

---

eyecite/utils.py
tests/test_ResolveTest.py

Hash function did not handle datetime and failed.

test and fix for issue #167

---

CHANGES.md
eyecite/models.py
tests/test_ModelsTest.py

This PR adds missing closing parentheses to the `corrected_citation_full` method in `FullCaseCitation` and `FullJournalCitation` classes. Additionally, I've added a test to prevent similar issues in the future.

fix(model): Tweaks the corrected_citation_full method

---

CHANGES.md
eyecite/tokenizers.py

This PR introduces logic to handle the `InvalidError` exception during loading the cached hyperscan db and fixes [#4053](https://github.com/freelawproject/courtlistener/issues/4053). 
According to the documentation, this error (`InvalidError`) is only returned when the function detects an invalid parameter. Since `loaddb` only takes one parameter(the serialized Hyperscan database), this error indicates a problem with the input ByteString. The current fix addresses this by triggering a full database recompile whenever this exception is encountered.

fix(hyperscan): Handles the InvalidError exception during db loading.

---

eyecite/annotate.py
eyecite/utils.py
tests/test_AnnotateTest.py

Some annotations, specially for ReferenceCitations, are discarded in HTML sources because some style tags (mostly i or em) are not balanced. This PR tries to include the style tags in the citation span
- Adds tests for `utils.maybe_balance_style_tags`
Solves #196

fix(annotate_citations): try to include HTML style tags if not balanced

---

eyecite/find.py
eyecite/helpers.py
eyecite/models.py
eyecite/resolve.py
tests/test_FindTest.py
tests/test_ResolveTest.py

Fixes #199
- updated ReferenceCitation and FullCaseCitation models metadata to admit resolved_case_name_short and resolved_case_name
- update helpers.filter_citations to save metadata of duplicated ReferenceCitations on the kept object
- update tests to show how the finding and resolution will work

feat(ReferenceCitation): use resolved_case_name and resolved_case_name_short for search and resolution

---

eyecite/regexes.py
tests/test_FindTest.py

Fix for #213 
Eyecite had a bug that could not generate short cite regex patterns for non standard regex variations.  
Anything with content between reporter and page,
Anything with parenthesis in the reporter all caused failures.  
This affected possibly 1537 variants.

Short cite regex bug

---

CHANGES.md
eyecite/utils.py
pyproject.toml
tests/test_AnnotateTest.py

Solves #229. Adds tests
Also, bump version to v2.6.11

fix(utils.maybe_balance_style_tags): use re.escape to form regex

---

CHANGES.md
eyecite/tokenizers.py
tests/test_FindTest.py

Solves #221 and #174
Uses a list of problematic nominative reporters to resolve overlpas
Due to the way we tokenize, an overlap was always resolved in favor of the first token. In the case of nominative reporters, this caused
a CitationToken to be found when a party name matched the
reporter's name, discarding the actual citation
This could be solved in a cleaner way by being consistent on tagging nominative reporters on reporters-db

fix(tokenizers): discard citation from nominative reporter on overlap

---

CHANGES.md
eyecite/utils.py
tests/test_AnnotateTest.py

Fixes #231
Allow searching beyond only whitespace for the missing style tag. This helps finding the missing tag when a party name or intro word ("see") are included in the style span. Added tests

fix(maybe_balance_style_tags): search further for missing tag

---

CHANGES.md
eyecite/find.py
eyecite/helpers.py
eyecite/models.py
eyecite/regexes.py
tests/test_FindTest.py

These complex styles were failing with square brackets and years before the citation.  Also addressed
an issue with extra running too long and
simplified the check for parallel citations
Meant to address complex citation patterns #185 
This does not address California parentheticals

feat(eyecite): Fix california style

---

CHANGES.md
benchmark/benchmark.py
eyecite/find.py
eyecite/models.py
tests/test_AnnotateTest.py
tests/test_FindTest.py
tests/test_ResolveTest.py

Add Document object for better citation parsing
With the introduction of markup parsing,
handling multiple parameters became unwieldy.
This PR creates a new `Document` object that encapsulates:
- Plain and markup text
- Span updates for text mapping
- Tokenized words and extracted citation tokens
This should simplify function calls and ultimately enable better HTML extraction.
Also simplify the get citations when using markup text only requiring markup text and cleaning steps 
Currently we must pre-process plaintext before parsing markup.

Simplify get citation call for markup

---

CHANGES.md
eyecite/regexes.py
tests/test_FindTest.py

Placeholder regexes overlapped in some instances with full case citations.  This PR removes the overlap by 
requiring placeholder citations to follow this ___ XXX ___ or - Nev. - format.  
Also, updated the placeholder to allow more known common placeholder reporter patterns.  
This should resolve this sentry issue.  
https://freelawproject.sentry.io/issues/6573913691/?project=5257254&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=1

Placeholder Citation Regex overlap

---

CHANGES.md
eyecite/helpers.py
tests/test_FindTest.py

Previously, a citation like "X v. Y 525 F. App’x 94, 103 n.15 (3d Cir. 2013) (quoting Iqbal, 556 U.S. at 686-87)" would lead to a warning "Unknown overlap case."
However this warning was written with the expectation that overlapping cases would be parallel citations, and that all parallel citations should be FullCaseCitations.
This PR updates the code to handle the case when there is a citation in a parenthetical, in which case the two cases would be overlapping, but do not have to both be FullCaseCitations.

fix(helpers): A citation in a parenthetical should not emit the warning "Unknown overlap case"

---

CHANGES.md
eyecite/helpers.py
eyecite/models.py
eyecite/regexes.py
tests/test_CourtsTest.py
tests/test_FindTest.py

As described in #242, there is currently a problem in detecting the court in a full citation when the parenthetical includes the specific date on which the opinion was issued, e.g., `(C.D. Cal. Feb. 9, 2015)`.
The problem is that we currently treat everything *before* the year as a potential court string, so `C.D. Cal. Feb. 9` in the example above. This causes the court lookup in `helpers.get_court_by_paren()` to fail.
This PR fixes this by modifying the `POST_FULL_CITATION_REGEX` regex to include capturing groups for potential months and days. If these are present, we capture them so the `<court>` group remains pristine (i.e., only `C.D. Cal.`). If they are not present, the behavior should be the same as it currently is.

Issue 242 - Fix court detection when parenthetical includes date

---

CHANGES.md
eyecite/annotate.py
eyecite/models.py
eyecite/utils.py
tests/test_AnnotateTest.py

@grossir 
We can use the placeholder markup from the start and avoid other unnecessary changes and 
downstream affects like changing CL or reinstantiating the offset updater.

feat(annotate): Use placeholder markup for annotating

---

.github/workflows/pdoc.yml
CHANGES.md
api_documentation/generate_documentation.sh

When `pdoc` creates our API docs, it automatically pulls in info for each parameter definition. This is a problem in the `get_citations()` doc because the `AhocorasickTokenizer` definition is crazy long. (See problem here: https://freelawproject.github.io/eyecite/#eyecite.get_citations.)
Therefore, we have a hack where we remove (using `sed`) this text from the docs after `pdoc` is run. However, this apparently stopped working at some point. The problem is that one of the parentheses in the regex is not escaped, which must now be required. This simple PR fixes this issue.

Fixes AhocorasickTokenizer regex replace for API docs
