tests/test_FindTest.py

See: freelawproject/reporters-db#42 and freelawproject/reporters-db#57

fix(tests): Remove last expected failures

---

README.rst

As suggested, appropriately enough, in #86.

Document hyperscan x86 installation requirements

---

TUTORIAL.ipynb

This PR should add the improvements suggested by @mlissner here: https://github.com/freelawproject/eyecite/pull/100#issuecomment-927225476
(To answer your other question, to edit this file, just run `jupyter notebook` in the project directory and it'll open a nice GUI for editing.)

More tutorial improvements (v3)

---

benchmark/benchmark.py

Small Pr to fix zip reading in benchmarking code

fix(benchmark): Bug in zip/bz2 code

---

.github/workflows/benchmark.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
README.rst

feat(readme): Update readme to include new CI notes

---

.github/workflows/benchmark.yml

Revert token for benchmarking workflow

fix(workflow): Revert token to freelawbot

---

poetry.lock
pyproject.toml

Bump Courts-db and Reporters-db

feat(poetry): Bump Reporters,Courts

---

.github/workflows/tests.yml
poetry.lock
pyproject.toml

Support python 3.11 and update dependencies

---

README.rst

Adds bibtex to the README for the paper... better late than never!

Add bibtex for JOSS paper

---

eyecite/models.py

This PR tweaks the code style of the span method to fix the issues reported by Black.

refactor(CitationBase): Updates style of the span method

---

.github/workflows/lint.yml
.github/workflows/pdoc.yml
.github/workflows/tests.yml

This PR adds a new step to the linting, testing, and pdoc action to create better keys to uniquely identify each version of our cache.

chore(github action): Add step to get python version and tweak cache key

---

eyecite/tokenizers.py

I found that eyecite doesn't work with the current version of hyperscan. This fixes the two compatibility errors I found. Github tests are locked to hyperscan version 0.2.0 because of poetry.lock, which I didn't mess with, so this isn't tested by CI.

Add compatibility for hyperscan 0.7.7

---

CHANGES.md
pyproject.toml

version bump v2.6.3

---

CHANGES.md
pyproject.toml

PR to release hyper scan bug fix

Version bump v2.6.4

---

eyecite/regexes.py

fix(regexes): add optional space to antecedent regexes

---

.github/workflows/check_changelog.yml
CHANGES.md

This PR adds a new workflow to verify that we added a new entry to CHANGES.md file.
If any of the changes do not require a new entry in the CHANGES.md file, you can add a label: no changelog to the PR to avoid the check and then run the action again.

feat(workflow): add workflow to check changelog changes

---

CHANGES.md
pyproject.toml

version bump v2.6.10

---

.github/workflows/tests.yml
CHANGES.md

fix(tests.yml): test workflow now uses ubuntu-latest

---

CHANGES.md
eyecite/annotate.py
eyecite/clean.py
eyecite/find.py
eyecite/helpers.py
eyecite/models.py

Useful for integration with CL
https://github.com/freelawproject/courtlistener/issues/5458
Also, add a `xml` in `clean.py`

fix(models.Document): identify source text and save a reference in Citation

---

CHANGES.md
eyecite/helpers.py
tests/test_FindTest.py

Small tweak and test
clean up of case names in plain text was removing An from the start of the case name

Fix case name bug

---

CHANGES.md
eyecite/helpers.py
tests/test_FindTest.py

Improve handling short case citations for plain text
Add boundary scan improvements around Supra,

refactor(helpers): Update boundary scan

---

CHANGES.md
pyproject.toml

version bump v2.7.4
